image: java:8u111-jdk-alpine

variables:
  GRAILS_VERSION: "4.0.0"
  GRADLE_VERSION: "5.1.1"
  GORM_VERSION: "7.0.2.RELEASE"

before_script:
  - apk update
  - apk add unzip
  - apk add zip
  - apk add bash
  - apk add curl
  - curl -sSL https://get.sdkman.io | bash
  - echo sdkman_auto_answer=true > /root/.sdkman/etc/config
  - bash -c ". /root/.sdkman/bin/sdkman-init.sh && sdk install gradle $GRADLE_VERSION < /dev/null && sdk use gradle $GRADLE_VERSION"
  - echo grailsVersion=$GRAILS_VERSION > gradle.properties
  - echo gormVersion=$GORM_VERSION >> gradle.properties
  - echo gradleWrapperVersion=$GRADLE_VERSION >> gradle.properties
  - ./gradlew --refresh-dependencies

build:
  script:
    - ./gradlew build
